### ISSUE TITLE
Thermostat doesn't turn on on set-temperature

### ISSUE THREAD

**Issue by 3v1n0** [nielsfaber/scheduler-component#142]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]

When scheduling to set temperature to a given value to my thermostat, it sets the temperature and turns it on if needed.

### Actual behavior
[What actually happened]

It sets the temperature, but doesn't turn on the heater.

### Steps to Reproduce
[Explain how to see the behaviour]

My heater is a tuya one that works with new tuya v2 platform (it used to work properly in this way), and its attributes are:

```yaml
hvac_modes:
  - 'off'
  - heat_cool
min_temp: 5
max_temp: 35
target_temp_step: 0.5
current_temperature: 18
temperature: 19
supported_features: 1
```

I've configured it in this way: ![image](https://user-images.githubusercontent.com/345675/140513191-d6ee96c3-0c1b-4183-acea-302e9e06beb1.png)

So that it turns off and after some time it turns on, but as you can see it didn't turn on, while the temperature is properly set.
And I don't have an UI button to turn it on (but it should be implicit in not being off).

**Comment by mdeweerd** [comment]
I am not opening a new issue, mine seems to be related.

# Summary
A schedule is supposed to act at 4AM to enable enable heating and set the temperature to 8°C.  Only the heating is set to the correct temperature.  

![image](https://user-images.githubusercontent.com/1504752/141281043-d5409ffb-3d11-452e-91bc-e09b587514ec.png)

# Detail
I have three Generic Thermostats in my system - Zigbee Temperature Sensors are used to control on/of relays.

Every day at 4AM, I programmed the scheduler to set the temperature to 8°C and to activate the Generic Thermostats.  The goal is to ensure that the temperature is set to a minimum and that the heating is on regardless of what happened during the day.

The schedule does set the Thermostat in heating mode, but does not set the temperature as the relays are actually enabled to increase the tempearture to the setpoints set at the end ov the day:
(top part= heaters active when green, bootom = tempeature measured (all above 14.5°C - the times are not perfectly aligned due to a graph "bug", but heating starts at 4AM):
![image](https://user-images.githubusercontent.com/1504752/141281510-aaa96fea-4e57-4f5f-8b2b-89768828a88d.png)

The schedule is called "Hors gel".

This is an extract from the journal:
![image](https://user-images.githubusercontent.com/1504752/141282269-9b809326-f4e1-42c9-843a-59bee77a2abf.png)

I am under the impression that only climate.set_hvac_mode is called and not set temperature.  Idealy climate.set_temperature is called just before setting the hvac_mode when switching on, and when switching off, set it just after changing the hvac mode (to avoid unnecessary heating if there is some delay between the settings).

**Comment by mdeweerd** [comment]
climate.set_temperature can also set the HVAC mode, so then there is no issue in the order the mode and temperature are set ;-).
I suggest to switch to climate.set_temperature.

**Comment by nielsfaber** [comment]
If you use the ‘heat’ action, scheduler will set the hvac_mode to ‘heat’ and 1 second later it sets the temperature setpoint to the value selected in the card.
This works fine for most users.

It could be that this doesn’t work with your climate device, either because it should not be in the ‘heat’ mode (some devices are 100% continuously ON at this mode) or because the 1 second delay is too short (there is also another open issue about this).


Please find out what is the cause. You could create a script or automation which performs the same sequence, and make alterations from there.

**Comment by mdeweerd** [comment]
This is the generic thermostat implementation of the Home Assistant core, so the temperature setting is managed on HA itself, not sent to the devices.  HA just receives the temperature from the device and then sends on/off commands to the relay.

Here is an extract from last night's journal.
We can see that "Hors gel" is triggered at 4:00AM and at 4:01AM  which corresponds to the initial trigger and the 1 minute delay.
I suppose that the services "set_hvac_mode" are called by the scheduler, and probably also the service events "climate.set_temperature" at 4:05 and 4:07 (and 04:14:06 not shown here).  

![image](https://user-images.githubusercontent.com/1504752/141683792-5ab98bea-6174-4c8c-b187-a08013492d37.png)

As indicated, the delay is strange, my Generic thermostat definitions look like this:
```
climate:
  - platform: generic_thermostat
    name: Principal
    heater: light.tz3000_5ng23zjs_ts0001_8d421efe_on_off
    target_sensor: sensor.principal_temperature
    min_temp: 7
    max_temp: 23
    ac_mode: false
    target_temp: 20.5
    min_cycle_duration: 60
    cold_tolerance: 0.3
    hot_tolerance: 0.2
    initial_hvac_mode: 'off'
    # away_temp: 7
    precision: 0.1
```

I think only the "climate.set_temperature" service is needed as it also allows to set the hvac mode (at least in the developer UI).

As this is not an automation as defined by HA, we can't see the graphs of what triggered and what was actioned, I do not know what is logged (I could activate logging).

I can have a look at the code, but not in the very near future.
