### ISSUE TITLE
Show "Name" in Planning overview

### ISSUE THREAD

**Issue by mdeweerd** [nielsfaber/scheduler-component#153]
I gave a name(/title) to each of my plannings, but in the following overview this is not used:
![image](https://user-images.githubusercontent.com/1504752/145086557-6decf9ca-b664-4c03-8fa6-41ea797e495f.png)

The Yaml configuration for that is the following
```yaml
  - title: Planning
    path: planning
    badges: []
    cards:
      - type: custom:scheduler-card
        time_step: 5
        include:
          - automation
          - climate
          - light
          - notify
          - scene
```

When the schedules are shown as on/off switches, the corresponding name is shown.

It would be nice to show the name also on the scheduler-card.  It's difficult to make the difference between "2xThermostat" and "2xThermostat" especially when they do not set the same Thermostats ;-).

**Comment by nielsfaber** [comment]
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/455

**Comment by mdeweerd** [comment]
I should have looked in the scheduler-card project of course.  Maybe an example or two could help there.

For the record, here is the card configuration I did following your feedback:
```yaml
type: custom:scheduler-card
time_step: 5
include:
  - automation
  - climate
  - light
  - notify
  - scene
display_options:
  primary_info:
    - '{name}: {action}'
    - additional-tasks
  secondary_info: relative-time
  icon: hass:action
```
