### ISSUE TITLE
templates in scheduler service

### ISSUE THREAD

**Issue by spriggsy** [nielsfaber/scheduler-component#165]
Im trying to use template to set the start time.
If I hard code the time to '12:00' then it creates the schedule correctly, However using the following code in a button card:

```
type: button
tap_action:
  action: call-service
  service: scheduler.add
  service_data:
    repeat_type: single
    name: Boost
    timeslots:
      start: {{ now().strftime("%H:%M") }}
      actions:
        - service: climate.set_hvac_mode
          entity_id: climate.downstairs
          service_data:
            hvac_mode: 'off'
  target: {}
show_state: false
icon: mdi:account
name: Boost
```

produces the following error when the card is pressed,
`Expected string or bytes like object`

it also reformats the button card code to the following: Note the start line.

```
type: button
tap_action:
  action: call-service
  service: scheduler.add
  service_data:
    repeat_type: single
    name: Boost
    timeslots:
      start:
        '[object Object]': null
      actions:
        - service: climate.set_hvac_mode
          entity_id: climate.downstairs
          service_data:
            hvac_mode: 'off'
  target: {}
show_state: false
icon: mdi:account
name: Boost

```

Ive seen in issue [https://github.com/nielsfaber/scheduler-component/issues/82](url) that templates seem to have been used, however not for me? 

Many thanks

Spriggsy
