### ISSUE TITLE
RGB colour wheel or similar

### ISSUE THREAD

**Issue by Kaibob2** [nielsfaber/scheduler-component#166]
### Checklist
- X I checked for similar existing requests (both open and closed) before posting.
- X My request is generic, other users may benefit from it too.

### Proposal
Would it be possible to have a colour wheel available or at least a field for a colour hex value or RGB values from 0-255?
I have several DIY RGB light with WS2812 Stripes connected to a ESP which runs ESPHOME. It would be great to be able to change the colour according to a timeslot schedule.

### Additional info
100% brightness R = 100 G = 50 B =10 from 8:00 until 10:00
50% brightness R = 255 G = 100 B =0 from 10:00 until 12:00
Off from 12:00 until 24:00

**Comment by nielsfaber** [comment]
I am not planning to implement a color picker in the card, because I expect it will barely be used (not much people want to change the color of a lamp on certain times).
It should be possible to create a custom action which allows you to set a color. I'm not sure about RGB since I think HA expects a list of R,G,B values rather than a string.
But perhaps adding the following might help you out:
```yaml
type: scheduler-card
# rest of card config
customize:
  light.my_color_lamp:
    actions:
      - service: light.turn_on
        name: "Turn on with color"
        icon: "mdi:lightbulb"
        variables:
          color_name:
            name: "Color name"
``` 
It should give a text field where you could put the name of the color you want.
I believe orangered / darkorange are more or less the colors you are looking for.

Alternatively, you could also create a script which accepts values for R,G,B and sets the light accordingly. 
You can create an action with sliders for R,G,B values in the scheduler-card, by defining min/max ranges (see [here](https://github.com/nielsfaber/scheduler-card#numeric-action-variable)).

I understand neither is ideal, but its what I can offer.

**Comment by Kaibob2** [comment]
Thanks for the explanation. I found a way to implement it which is absolutely satisfactory for me:
```
customize:
  light.nachtlicht_kizi:
    actions:
      - service: light.turn_on
        name: Turn on with color
        icon: mdi:lightbulb
        variables:
          color_name:
            name: Farbname
            options:
              - value: red
                name: Rot
              - value: orange
                name: Orange
              - value: darkorange
                name: Dunkelorange
              - value: orangered
                name: Orangerot
              - value: deeppink
                name: Pink
          brightness_pct:
            name: Helligkeit
            min: 1
            max: 100
```

A list of possible colors can be found here: https://htmlcolorcodes.com/color-names/

This makes it even easier as i can copy/paste it for different schedules. Many thanks for the hint.

![SharedScreenshot](https://user-images.githubusercontent.com/20832276/148512361-e0073ad0-9e4d-41c6-9a7d-48d5b9497f07.jpg)
