### ISSUE TITLE
Add current slot action to switch. attributes

### ISSUE THREAD

**Issue by florianec** [nielsfaber/scheduler-component#174]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
My Idea is to add the current slot action as an attribute: **current_slot_action:**

### Additional info

This is what it would look like:
```
weekdays: daily
times: 00:00:00, 06:00:00, 23:00:00
actions: 
- service: climate.set_temperature
  entity_id: climate.bad
  service_data:
    hvac_mode: heat
    temperature: 18
- service: climate.set_temperature
  entity_id: climate.bad
  service_data:
    hvac_mode: heat
    temperature: 20

current_slot: 1
current_slot_action:
- service: climate.set_temperature
  entity_id: climate.bad
  service_data:
    hvac_mode: heat
    temperature: 20
next_slot: 2
next_trigger: 2022-01-31T23:00:00+01:00
tags: 
icon: mdi:calendar-clock
friendly_name: Bad Heizung
```

It could then be used in automations, templates, scripts etc.
