### ISSUE TITLE
Thermostat temperature not updating (similar to 96, 133 and 136 I think)

### ISSUE THREAD

**Issue by jal142** [nielsfaber/scheduler-component#181]
### Checklist
- [x ] I checked for similar existing issues (both open and closed) before posting.
- [x ] I am running the latest version.

### Expected behavior
Running a Honeywell T6 Zwave thermostat.  Using a scheme with the "regulate" option that should be updating the set temperature range at 7:30am.  

### Actual behavior
The temperature range remains at the same points as it was overnight.  However, if I trigger the scheme manually by editing the range and clicking "save", it updates successfully.

### Steps to Reproduce
In the log, when the scheduler runs, I see this:
Schedule #ad7b05 turned on
7:31:00 AM - 4 hours ago
T6 Pro Z-Wave Programmable Thermostat changed to Heat/Cool
7:30:10 AM - 4 hours ago
T6 Pro Z-Wave Programmable Thermostat changed to Cool by service climate.set_temperature
7:30:00 AM - 4 hours ago
Schedule #ad7b05 changed to triggered

When I manually triggered the scheme by editing the range and clicking save, I see this:
T6 Pro Z-Wave Programmable Thermostat changed to Heat/Cool by service climate.set_hvac_mode
10:33:14 AM - 1 hour ago
T6 Pro Z-Wave Programmable Thermostat changed to Cool by service climate.set_temperature
10:33:09 AM - 1 hour ago

Again, the scheduler command sequence (at 7:30 am) did not update the temperature.  The second set of commands at 10:33 am did update the range.  for completeness, I'm trying to set the temperature range from 65-75F overnight to 68-79F during the day.  When I checked the thermostat at 10 am this morning, it was still at the 65-75F setting.

I see two differences in the logs:
1. The delay between the commands is 10 seconds when the scheduler sent them, but it is only 5 seconds when it was done manually.
2. The scheduler message for the Heat/Cool change is missing the "by service climate.set_hvac_mode"

In reading the other issues (133 and 136), I got the impression that the delay was upped to 10 seconds to address this issue.  That fix does not appear to work for my setup (T6 thermostat, Zoos ZST10 Z-Wave USB stick, nothing else on the Z-Wave network at this point).  

I am confused by the messages in the log.  Why is the code is sending a "Cool" command followed by a "Heat/Cool" command.  Or is the first "Cool" command actually the command to set the cooling temperature?  I assume the "Regulate" option is equivalent to the "Heat/Cool" command.  Should I not be using this?

**Comment by Kingo71** [comment]
Same here, sometime is working other not. 
Was working with custom component "simple thermostat", failing now with another custom component "better thermostat".

**Comment by nielsfaber** [comment]
The 'regulate' action does the following:
1. Call service `set_hvac_mode` with `hvac_mode=heat_cool`
2. Wait 5 seconds
3. Call service `set_temperature` with `target_temp_low=<first slider value>` and `target_temp_high=<second slider value>` and `hvac_mode=heat_cool`

These services are described [here](https://www.home-assistant.io/integrations/climate/).
In some cases only step 3 would be sufficient, but a lot of integrations don't support setting the `hvac_mode` directly via the `set_temperature` service.

I am unable to reproduce your issue since I use different integration.
Therefore it would be helpful if you can troubleshoot the issue yourself.

First off, you could enable debug logging for the scheduler integration, by adding this to the configuration.yaml (and reloading HA):
```yaml
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```
This will result in additional loggings in the HA log. You can track exactly which service is called by scheduler and when (although not the exact parameters will be displayed).

Second, you could define a [script](https://www.home-assistant.io/integrations/script/) to 'mimic' the sequence which scheduler performs.
Example:
```yaml
thermostat_test:
  sequence:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.my_climate  #replace by correct entity
        hvac_mode: heat_cool
    - delay: 5
    - service: climate.set_temperature
      data:
        entity_id: climate.my_climate #replace by correct entity
        target_temp_low: 68
        target_temp_high: 79
        hvac_mode: heat_cool
```

I would assume executing this script has the same behaviour as the action performed by scheduler.
If the thermostat doesn't respond well to it either, the problem might be with the device itself.

Please let me know your findings.
