### ISSUE TITLE
Scheduler doesn't set temperature of thermostat preset

### ISSUE THREAD

**Issue by senky** [nielsfaber/scheduler-component#184]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Scheduler to set correct preset and its temperature after HA restart.

### Actual behavior
Preset is set, but default temperature stays instact.

### Steps to Reproduce
Use this generic_thermostat config:
```
climate:
  - platform: generic_thermostat
    name: Heater
    heater: switch.thermostat
    target_sensor: sensor.temperature
    min_temp: 18
    max_temp: 24
    target_temp: 22
    min_cycle_duration:
      minutes: 30
    cold_tolerance: 0.7
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    away_temp: 18
    sleep_temp: 18
```
Set scheduler like this:
<img width="501" alt="Snímka obrazovky 2022-02-18 o 20 38 47" src="https://user-images.githubusercontent.com/182498/154750471-e8105439-cf0e-4972-820d-3c2f25b45bf0.png">

After 8:00pm restart HA. Observe thermostat is set to "sleep" preset, but temperature stays at 22°C:
 
<img width="338" alt="Snímka obrazovky 2022-02-18 o 20 40 22" src="https://user-images.githubusercontent.com/182498/154750695-3d14607a-272f-4ab5-9a82-6da0125c6887.png">
