### ISSUE TITLE
"Supervision" or "Enforcing" option for timeslots

### ISSUE THREAD

**Issue by kdknigga** [nielsfaber/scheduler-component#197]
### Checklist
- [ X] I checked for similar existing requests (both open and closed) before posting.
- [ X] My request is generic, other users may benefit from it too.

### Proposal
An option to monitor the states of "actioned" entities and keep them in the desired state would be neat.  For example, I have a schedule to turn on and off outside lights.  But, sometimes during the time period where the lights are supposed to be on someone in the house will turn the switch off.  Currently, the lights just stay off until another "on" timeslot comes up.  If the switch state could be monitored then the switch could be automatically turned back on (perhaps with a delay so an unknowning human doesn't get into a fight with the automation).

Great component, and thanks a lot!

**Comment by kdknigga** [comment]
I just had another idea that might accomplish the same thing but be easier to implement (at least, in scheduler).

What about just having "names" for timeslots that show up as attributes?  The name could be simply "On", "Off", or "None" based on the action assigned to the timeslot, but perhaps with the option for custom names.  Then a separate, user-made automation could key off of the timeslot name in its decision making.

So `switch.schedule_foo` would have attributes like:

```
current_slot: 2
current_slot_name: 'On'
next_slot: 3
next_slot_name: 'Off'
```

**Comment by kdknigga** [comment]
Not stale.

**Comment by nielsfaber** [comment]
I am sorry for the lack of response from my side.
Regarding your original request:
> But, sometimes during the time period where the lights are supposed to be on someone in the house will turn the switch off. Currently, the lights just stay off until another "on" timeslot comes up. If the switch state could be monitored then the switch could be automatically turned back on.

A possible way to achieve this functionality is by adding a condition to a schedule, e.g. the light must be OFF.
You can use this setting to make the schedule re-trigger when the conditions change: 
<img src="https://user-images.githubusercontent.com/16861605/172421485-262c2f0d-bb9c-487b-a138-b13b187464cd.png" width="50%" height="50%">
As a result, the scheduler will turn the lamp back ON as soon as someone tuned it OFF.
Obviously this schedule will work for timeslots containing actions to turn on (due to the assigned conditions). 
You may need a second schedule for the opposite actions. 
It is currently not possible to define conditions per timeslot.

> perhaps with a delay so an unknowning human doesn't get into a fight with the automation

If you want to have a delay you may need to create a [template entity](https://www.home-assistant.io/integrations/template/#delay_on) mirroring the state of the lamp with the desired delay, and use this entity for the condition instead of the actual lamp.
Within scheduler it is currently not possible to delay the re-triggering (perhaps in the future).

Regarding your second request:
> What about just having "names" for timeslots that show up as attributes? The name could be simply "On", "Off", or "None" based on the action assigned to the timeslot, but perhaps with the option for custom names. Then a separate, user-made automation could key off of the timeslot name in its decision making.

Users are not asked to name the timeslots, this would overcomplicate the card. 
The name assigned to a timeslot is based on the assigned action (timeslots without actions are blank, and ignored by scheduler component).
Scheduler entities expose the number of the current and next timeslots, as well as a list of actions for each timeslot:
<img src="https://user-images.githubusercontent.com/16861605/172423818-0abf9633-cdcc-4ce7-adda-9e0b06fcc313.png" width="75%" height="75%">
<img src="https://user-images.githubusercontent.com/16861605/172424387-e809f055-edb1-49d7-8b33-285e2dc2d060.png" width="50%" height="50%">
With this data you should be able to determine which action is currently active in some script or automation (ofcourse it requires some decoding work, but unfortunately not all actions in HA are simple on/off).
You could use the `scheduler.run_action` service to manually re-trigger the action for a certain timeslot.

It seems that you should be able to achieve your goal in both ways. 
At this point I don't see anything that is missing in scheduler, so I think your request can be closed.

**Comment by clau-bucur** [comment]
I have a scenario where I need something similar: I have a set of heating schedules based on different _house states_ (guests, homeoffice, holiday, away, etc). For each of these states I create a group of schedules controlling different climate devices. This gives me now 5 groups with schedules (switch entities).
Then an automation to enable only the required group based on the current _house state_.
The problem I face is that when a group is enabled (so it's schedule swiches are turned on) the schedule does not activate the action for it's current timeslot (so it's not setting the climate to the desired set temperature).

I tried to raise this on the forum topic but had no luck with it, so I came up with a python helper script that would run the action of the current timeslot for the entity_id it gets as input (it accepts groups also and it executes on every entity in the group).

You can use this script also, in an automation, to keep enforcing your schedule as you wish. You also have the flexibility of specifing the delays you need or other conditions you can think of.
You need to have enabled [Python Scripts](https://www.home-assistant.io/integrations/python_script/) then place this in **python_scripts** folder
**activate_schedule.py**:
```
def flatten(entity_id, result=[], searched=[]):
    state = hass.states.get(entity_id)

    if state is not None:
        entity_ids = state.attributes.get("entity_id")
        if entity_ids is not None:
            searched.append(entity_id)
            for entity_id in entity_ids:
                if entity_id not in result and entity_id not in searched:
                    flatten(entity_id, result, searched)
        else:
            result.append(entity_id)

def activate(entity_id, is_workday, allow_turn_on):
    logger.debug("%s - operating schedule", entity_id)
    schedule_entity = hass.states.get(entity_id)

    if schedule_entity.state == 'off':
        if not allow_turn_on:
            logger.warning("%s - schedule switch turned off, skipping", entity_id)
            return

        logger.info('%s - turning on schedule switch', entity_id)
        hass.services.call('switch', 'turn_on', { 'entity_id': entity_id }, True)
        schedule_entity = hass.states.get(entity_id)

    if schedule_entity.state != 'on':
        logger.error('%s - schedule switch not turned on, skipping', entity_id)
        return

    weekdays = schedule_entity.attributes.get("weekdays")
    timeslots = schedule_entity.attributes.get("timeslots")
    actions = schedule_entity.attributes.get("actions")
    current_slot = schedule_entity.attributes.get("current_slot")
    should_activate = False

    logger.debug(" weekdays: {0}; actions: {1}; timeslots: {2}; current_slot: {3}, is_workday: {4}".format(weekdays, actions, timeslots, current_slot, is_workday))

    #if current_slot is set, then we're on an active slot so it requires activation
    if current_slot is not None:
        should_activate = True
        action = actions[current_slot]

    #daily always gets activated or if one timeslot only then workday schedule gets activated during workday and weekend schedule gets activated during weekend
    elif weekdays[0] == 'daily' or (len(timeslots) == 1 and weekdays[0] in ('workday' if is_workday else 'weekend')):
        should_activate = True
        action = actions[0]

    logger.debug(" ==> should_activate: {0}".format(should_activate))
    if should_activate:
        if 'data' in action:
            action['data']['entity_id'] = schedule_entity.attributes.get("entities")[0]
        else:
            action['data'] = { "entity_id": schedule_entity.attributes.get("entities")[0] }

        logger.debug("{0} - activating schedule with action {1}".format(entity_id, action))
        hass.services.call(action['service'].split('.')[0], action['service'].split('.')[1], action['data'], False)


entity_id = data.get("entity_id")
allow_turn_on = data.get("allow_turn_on") if data.get("allow_turn_on") else False
state = hass.states.get(entity_id)

if entity_id is None or state is None:
    logger.error("Entity ID not provided or does not exist: %s", entity_id)
else:
    logger.info('%s - activate schedule', entity_id)
    if state.state == 'off' and not allow_turn_on:
        logger.warning("%s - schedule switch turned off, skipping activation", entity_id)
    else:
        if state.state == 'off':
            logger.info('%s - turning on schedule switch', entity_id)
            hass.services.call('switch', 'turn_on', { 'entity_id': entity_id }, True)

        entity_ids = []
        flatten(entity_id, entity_ids)

        is_workday = hass.states.get('binary_sensor.workday_sensor').state == 'on'
        for entity in entity_ids:
            activate(entity, is_workday, allow_turn_on)
```
**services.yaml**:
```
activate_schedule:
  name: Activate Schedule or Schedule Group
  description: Turn on a specific light and set its color.
  fields:
    entity_id:
      description: The schedule or schedules group to activate.
      example: group.schedule_heating
    allow_turn_on:
      description: Automatically turn the schedule on if it's turned off. Otherwise will skip schedule activation.
      example: true
```

This is my code that runs it:
```
automation:
  - alias: Heating / House State / Auto
    id: "1653376525"
    description: Activate heating schedules based on the current state of the house_state.
    mode: queued
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.house_state
    action:
      service: script.heating_auto_mode

script:
  heating_auto_mode:
    variables:
      house_state: "{{ states('sensor.house_state') }}"
      heating_season: "{{ is_state_attr('sensor.house_state', 'heating_season', 'on') }}"
      guest: "{{ state_attr('sensor.house_state', 'guest') }}"
      homeoffice: "{{ state_attr('sensor.house_state', 'homeoffice') }}"
    sequence:
      - service: script.debug_notification
        data:
          condition_entity: input_boolean.debug_heating
          title: Heating Auto Mode
          message: "house_state {{ house_state }}; heating_season {{ heating_season }}; guest {{ guest }}; homeoffice {{ homeoffice }}"

      - condition: "{{ house_state != 'invalid' }}"
      - service: script.heating_activate_group
        data:
          heating_group: >
            {% if not heating_season %}
              group.schedule_heating_offseason
            {% elif house_state == 'armed_away' %}
              group.schedule_heating_away
            {% elif house_state in ('armed', 'armed_nearby') %}
              group.schedule_heating_armed
            {% elif guest == 'sanctuary' %}
              group.schedule_heating_guest_sanctuary
            {% elif guest == 'office' %}
              group.schedule_heating_guest_office
            {% elif guest == 'on' %}
              group.schedule_heating_guests
            {% elif homeoffice == 'sanctuary' %}
              group.schedule_heating_homeoffice_sanctuary
            {% elif homeoffice == 'office' %}
              group.schedule_heating_homeoffice_office
            {% elif homeoffice == 'on' %}
              group.schedule_heating_homeoffice
            {% else %}
              group.schedule_heating_home
            {% endif %}

  heating_activate_group:
    mode: queued
    variables:
      heating_group: group.schedule_heating_home
    sequence:
      - service: switch.turn_off
        entity_id: group.schedule_heating_all
      - service: python_script.activate_schedule
        data:
          allow_turn_on: true
          entity_id: "{{ heating_group }}"

group:
  schedule_heating_home:
    name: Schedules while HOME
    entities:
      - switch.schedule_heating_living_home

      - switch.schedule_heating_bedroom_home
      - switch.schedule_master_bedroom_home
      - switch.schedule_master_bedroom_weekend_home

      - switch.schedule_heating_sanctuary_home
      - switch.schedule_heating_sanctuary_weekend_home
      - switch.schedule_master_sanctuary_home

      - switch.schedule_heating_office_home
      - switch.schedule_heating_office_weekend_home
      - switch.schedule_master_office_home

  schedule_heating_away:
    name: Schedules while AWAY
    entities:
      - switch.schedule_heating_living_away
      - switch.schedule_heating_bedroom_away
      - switch.schedule_master_bedroom_away
      - switch.schedule_heating_sanctuary_away
      - switch.schedule_master_sanctuary_away
      - switch.schedule_heating_office_away
      - switch.schedule_master_office_away

  schedule_heating_armed:
    name: Schedules while ARMED
    entities:
      - switch.schedule_heating_living_away
      - switch.schedule_heating_bedroom_away
      - switch.schedule_master_bedroom_away
      - switch.schedule_heating_sanctuary_away
      - switch.schedule_master_sanctuary_away
      - switch.schedule_heating_office_away
      - switch.schedule_master_office_away

  schedule_heating_guest_office:
    name: Schedules while GUEST in the Office
    entities:
      - switch.schedule_heating_living_home
      - switch.schedule_heating_bedroom_home
      - switch.schedule_master_bedroom_home
      - switch.schedule_master_bedroom_weekend_home

      - switch.schedule_heating_office_guest
      - switch.schedule_master_office_guest

  schedule_heating_guest_sanctuary:
    name: Schedules while GUEST in the Sanctuary
    entities:
      - switch.schedule_heating_living_home
      - switch.schedule_heating_bedroom_home
      - switch.schedule_master_bedroom_home
      - switch.schedule_master_bedroom_weekend_home

      - switch.schedule_heating_sanctuary_guest
      - switch.schedule_master_sanctuary_guest

  schedule_heating_guests:
    name: Schedules while GUESTS
    entities:
      - group.schedule_heating_guest_office
      - group.schedule_heating_guest_sanctuary

  schedule_heating_homeoffice_office:
    name: Schedules while HOMEOFFICE in the Office
    entities:
      - switch.schedule_heating_living_home
      - switch.schedule_heating_bedroom_home
      - switch.schedule_master_bedroom_home
      - switch.schedule_master_bedroom_weekend_home

      - switch.schedule_heating_office_homeoffice
      - switch.schedule_master_office_homeoffice

  schedule_heating_homeoffice_sanctuary:
    name: Schedules while HOMEOFFICE in the Sanctuary
    entities:
      - switch.schedule_heating_living_home
      - switch.schedule_heating_bedroom_home
      - switch.schedule_master_bedroom_home
      - switch.schedule_master_bedroom_weekend_home

      - switch.schedule_heating_sanctuary_homeoffice
      - switch.schedule_master_sanctuary_homeoffice

  schedule_heating_homeoffice:
    name: Schedules while HOMEOFFICE
    entities:
      - group.schedule_heating_homeoffice_office
      - group.schedule_heating_homeoffice_sanctuary

  schedule_heating_offseason:
    name: Schedules while OFF SEASON
    entities:
      - switch.schedule_heating_living_offseason

      - switch.schedule_heating_bedroom_offseason
      - switch.schedule_master_bedroom_offseason

      - switch.schedule_heating_sanctuary_offseason
      - switch.schedule_master_sanctuary_offseason

      - switch.schedule_heating_office_offseason
      - switch.schedule_master_office_offseason

  schedule_heating_all:
    name: All heating schedules
    entities:
      - group.schedule_heating_home
      - group.schedule_heating_away
      - group.schedule_heating_guests
      - group.schedule_heating_homeoffice
      - group.schedule_heating_offseason

```
