### ISSUE TITLE
Step size of temperature slider

### ISSUE THREAD

**Issue by ltjessem** [nielsfaber/scheduler-component#244]
Is there a way to either increase the step size of the temperature slider, for example to 0.5 or 1°C, or to decrease its range?

Reason being is that it's difficult to select say 20°C without flopping back and forth between 19.9 and 20.1 on mobile. For my particular use case the range of 7-35°C is also too large and makes it even more difficult to select the exact temperature I need.

**Comment by ltjessem** [comment]
Still an issue

**Comment by nielsfaber** [comment]
The timestep used by the card is defined by your climate device.
If you want to customize this, please follow the procedure here: https://github.com/nielsfaber/scheduler-card#customizing-built-in-actions (note that the `step` parameter defines the step size.

**Comment by ltjessem** [comment]
I can't find anything there that would solve this. You're thinking of time step while I'm talking about temp step.
![image](https://user-images.githubusercontent.com/10084953/225882318-80c0f76c-a0e8-4fe9-aaf8-e96eceaecaab.png)

**Comment by ltjessem** [comment]
Still relevant.

**Comment by nielsfaber** [comment]
> I can't find anything there that would solve this. You're thinking of time step while I'm talking about temp step.

No I'm not.
In my previous response I pointed to this code example:
```yaml
customize:
  climate.my_tuya_thermostat:
    exclude_actions:
      - heat       # hide the built-in action to avoid duplicates
      - set mode   # we won't use this
      - set preset # we won't use this
    actions:       # add the custom actions
      - service: set_temperature
        service_data:
          hvac_mode: auto
        variables:
          temperature:
            min: 10
            max: 25
            step: 0.5
            unit: '°C'
        icon: 'hass:fire'
        name: "heat[ to {temperature}]" # replace with local translation for 'heat' and 'to' if desired
```

the section `variables` defines the settings for the temperature slider. So you can set your own range (min/max) and also the step size for the slider.
By default, the card will follow the setting of your climate device (`target_temp_step` property).
