### ISSUE TITLE
Scheduled action not executed when state of person is unknown

### ISSUE THREAD

**Issue by pomeloy** [nielsfaber/scheduler-component#263]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version v3.2.14.

### Expected behavior
Scheduled action takes place

### Actual behavior
Scheduled action does not take place
Logs empty

### Steps to Reproduce

- Create any schedule, conditions should include a person (current state "unknown")
  - either as one of several conditions checking whether at least one of several person entities has the state "home" (wherein at least one of the other persons is home)
  - or as singular condition ("person NOT at home")

Actions never get executed whenever a person with unknown state is included in one of the conditions, whereas native automations work flawlessly, e.g. 

```
condition: not
conditions:
  - condition: state
    entity_id: person.person
    state: home
```
