### ISSUE TITLE
[issue] not start scheduler after restart (with condition)

### ISSUE THREAD

**Issue by devildant** [nielsfaber/scheduler-component#299]
Hello,

when i restart Home assistant the schedules no longer run, all my schedules have conditions on device trackers, and after a reboot, despite the change in status of the device tracker, the schedules are no longer activated.

to return to normal use I have to deactivate them via the card, and reactivate them (to fix this temporarily, I created an automation which when starting home assistant deactivates the schedules and reactivates them)

ps: thank you for this planner, great job

**Comment by apas2** [comment]
hello
same here
but i dont manage to refresh it
could you show your automation please ?

**Comment by devildant** [comment]
> hello same here but i dont manage to refresh it could you show your automation please ?

yes if you want, i juste change switch on/off to run service scheduler

```
alias: 0001-Schedule-Action-Reload-Chauffage
description: ""
trigger: []
condition: []
action:
  - service: scheduler.run_action
    data:
      entity_id: switch.schedule_chauffage_salon_absent
  - service: scheduler.run_action
    data:
      entity_id: switch.schedule_chauffage_salon_present
  - service: scheduler.run_action
    data:
      entity_id: switch.schedule_chauffage_chambre_absent
  - service: scheduler.run_action
    data:
      entity_id: switch.schedule_chauffage_chambre_present
  - service: scheduler.run_action
    data:
      entity_id: switch.schedule_chauffage_salle_de_bain_absent
  - service: scheduler.run_action
    data:
      entity_id: switch.schedule_chauffage_salle_de_bain_present
mode: single

```
