### ISSUE TITLE
condition re-evaluation doesn't work after core restart

### ISSUE THREAD

**Issue by luka6000** [nielsfaber/scheduler-component#305]
Condition re-evaluation doesn't work after HA core restart as described [here](https://community.home-assistant.io/t/scheduler-card-custom-component/217458/1909?u=luka6000)

### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]

set schedule with conditions. Mark "re-evaluate conditions". Schedule should re-evaluate conditions all the time.

### Actual behavior
[What actually happened]
Schedule is not re-evaluating conditions after HA core restart. One needs to disable and reenable schedule to make it work.

Only thing I can find in the logs is this
```
2023-10-22 20:53:38.865 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 407d37 was already executed before shutdown, initial timeslot is skipped.
```
So maybe the slot that schedule is in after restart is skipped?

### Steps to Reproduce
[Explain how to see the behaviour]
1. set schedule with conditions. Mark "re-evaluate conditions".
2. check if re-evaluation works (like use input_boolean of similar to easily trigger conditions change)
3. restart ha
4. check if re-evaluation still works

**Comment by patriiiiiiiiiick** [comment]
The issue is with the active schedules, right? I mean, if I restart HA at 23.30, will conditions be evaluated again at midnight?

**Comment by luka6000** [comment]
Yes ofc. The schedule is active and does not work after ha restart. I’m not sure about it working on next timeslot. I already have automation restarting every scheduler after restart

**Comment by johndfoss** [comment]
I have the same problem of schedules not re-evaluating conditions even without HA restart.

**Comment by devildant** [comment]
hello, I see the same problem, I did an automation to temporarily overcome the problem:

```
description: ""
mode: single
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - repeat:
      sequence:
        - if:
            - condition: template
              value_template: "{{ states(repeat.item) == 'on' }}"
          then:
            - service: scheduler.run_action
              data:
                entity_id: "{{ repeat.item }}"
              enabled: true
        - delay:
            hours: 0
            minutes: 0
            seconds: 1
            milliseconds: 0
      for_each: |
        {{ integration_entities('scheduler') }}
    enabled: true
```
