### ISSUE TITLE
Adding schedule switch from developer tools crashes my scheduler as of 2024.3

### ISSUE THREAD

**Issue by robertoleonardo** [nielsfaber/scheduler-component#337]
### Checklist
- [ x] I checked for similar existing issues (both open and closed) before posting.
- [x ] I am running the latest version.

### Expected behavior
Prior to updating to home assistant stable version last week (2024.3), i could add scheduled tasks via script/developer tools. for example, this worked fine: 

```

service: scheduler.add
data:
  timeslots:
    - start: "12:00"
      actions:
        - service: fan.turn_off
          entity_id: fan.pure_hot_cool_link
          service_data: {}
  repeat_type: single
  name: Turn Off Dyson
```

### Actual behavior
After upgrading, the scheduler component loads fine on a reboot and i see my scheduler card and schedule switches, but as soon as any script wiht a scheduler.add runs (or i run one manually in developer tools), the whole scheduler component crashes.  my scheduler card disappears entirely and i have to reboot home assistant (and then it crashes once again as soon as i try to add anything else via script/developer tools)

this is what my logs say about it:  
```

File "/config/custom_components/scheduler/const.py", line 108, in validate_date
2024-03-10 20:27:00.240 ERROR (MainThread) [homeassistant.util.logging] Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('ab40c4',)
File "/config/custom_components/scheduler/switch.py", line 218, in async_timer_updated
2024-03-10 20:27:00.248 ERROR (MainThread) [homeassistant.util.logging] Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('f92019',)
File "/config/custom_components/scheduler/switch.py", line 218, in async_timer_updated
```

here is the portion of switch.py that it's taking issue with.  i am not skilled enough to know how to tweak this to fix whatever the logs are saying is wrong, however:
```

         if self._state not in [STATE_OFF, STATE_TRIGGERED]:
            if len(self._next_entries) < 1:
                self._state = STATE_UNAVAILABLE
            else:
                now = dt_util.as_local(dt_util.utcnow())
                if (self._timer_handler._next_trigger - now).total_seconds() < 0:
                    self._state = const.STATE_COMPLETED
                else:
                    self._state = (
                        STATE_ON if self.schedule[const.ATTR_ENABLED] else STATE_OFF
                    )

```
###STEPS TO REPRODUCE
happens every time i use script/developer tools to try to add a scheduled event.  i've noticed that after i reboot, the scheduled item iw as trying to add does appear and does run, but only if i reboot after the crash but before the event was scheduled to run.   and then as soon as it runs and tries to delete a 1 time event, it crashes again.

**Comment by robertoleonardo** [comment]
FYI this issue is persisting for me even after updating today to 2024.3.1

**Comment by robertoleonardo** [comment]
issue persists for me in today's scheduler component 3.3.2 update

**Comment by nielsfaber** [comment]
Try replacing 12:00 by 12:00:00.
This is how scheduler-card sends time information to the component.

**Comment by robertoleonardo** [comment]
i'll give it a shot. fyi in the meantime i created an automation that reloads the scheduler integration every time an event is added or edited and that seems to address the issue. but i'll give your more elegant suggestion a shot. thanks!



--
rob lee
m: 310.431.1619
________________________________

**Comment by robertoleonardo** [comment]
sorry i meant to come back sooner -- this didn't fix it for me. my workaround is pretty seamless so this isn't a pressing issue, but just wanted to flag that the issue persists.

**Comment by shlomki** [comment]
I've just tried the time trick too and it didn't work unfortunately. @robertoleonardo  What's your workaround? Restarting HA?
Unfortunately that's not a good workaround for me because I'm trying to add a new schedule from lovelace. I can't restart HA every time...

BTW I opened the same bug under the scheduler-card repository, but only now I realized that the integration has a separate repository.
https://github.com/nielsfaber/scheduler-card/issues/809

**Comment by robertoleonardo** [comment]
oh, no, rebooting would be a pain. there's a better way -- automation that reloads the scheduler integration every time scheduler add and scheduler edit service runs. those seem to be the two services that cause it to crash.

you've just gotta set up an event listener trigger for those two services and then there's a way to reload integration by service as well.

i'm in bed right now but i can send you the automation yaml tomorrow if you'd like.

ive been pleasantly surprised -- its proven to be a pretty reliable and quick and seamless workaround. didn't need to reconfigure anything -- just added the automation and everything was up and running again.



--
rob lee
m: 310.431.1619
________________________________

**Comment by robertoleonardo** [comment]
here's the yaml for my workaround automation.  reloads scheduler every 5 minutes and immediately upon and scheduler service event.  in UI mode, just look for "Scheduler" under device options once you select the reload config entity option.  

```
alias: Reload Scheduler (Automation)
description: ""
trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: scheduler
  - platform: time_pattern
    hours: "*"
    minutes: /5
    seconds: "0"
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      device_id: 546abe93cc9676807254f7992dd79f86
mode: single

```
