### ISSUE TITLE
Problem updating timeslots from action/service call

### ISSUE THREAD

**Issue by carlos-48** [nielsfaber/scheduler-component#431]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Update timeslots of an existing schedule

### Actual behavior
Updates the timeslots but it says "Invalid date" in the card.

![Image](https://github.com/user-attachments/assets/c77793fa-2a8d-4aeb-bc96-9db62a5977c3)

![Image](https://github.com/user-attachments/assets/e59faaab-5386-4ce2-a698-96c1c2a410b6)

![Image](https://github.com/user-attachments/assets/035b195e-89c2-442e-91d7-7e858e001c49)

![Image](https://github.com/user-attachments/assets/6ba08548-59ee-4294-ac4f-20daa15e4b33)

Also tried stoping the last slot at "00:00" instead of "23:59"

### Steps to Reproduce
Exectute the next action:

```
action: scheduler.edit
data:
  entity_id: switch.schedule_calefaccion_dias_laborales
  timeslots:
    - start: "00:00"
      stop: "04:00"
      actions:
        - entity_id: climate.aire
          service: climate.set_hvac_mode
          service_data:
            hvac_mode: "off"
    - start: "04:00"
      stop: "06:00"
      actions:
        - entity_id: climate.aire
          service: climate.set_hvac_mode
          service_data:
            hvac_mode: "heat"
        - entity_id: climate.aire
          service: climate.set_temperature
          service_data:
            temperature: 22
    - start: "06:00"
      stop: "23:59"
      actions:
        - entity_id: climate.aire
          service: climate.set_hvac_mode
          service_data:
            hvac_mode: "off"
```
