### ISSUE TITLE
Schedules failed at night when DST change happened

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/scheduler-component#436]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
Schedules to be executed as defined even at DST change night.

### Actual behavior
At night March 29/30, when daylight savings time activated at 3:00, some of my schedules failed to execute at proper times.
To demonstrate - adding screenshots of couple of previous days and mentioned night, as well as schedules config:

![Image](https://github.com/user-attachments/assets/c9abe167-9e4e-4e4d-a902-4fe984c97ebb)
```
weekdays: daily
timeslots: 00:00:00 - 03:00:00, 03:00:00 - 06:00:00, 06:00:00 - 22:00:00, 22:00:00 - 00:00:00
entities: climate.sth_bathr1
actions: 
- service: climate.set_temperature
  data:
    hvac_mode: heat
    temperature: 21
- service: climate.set_temperature
  data:
    hvac_mode: heat
    temperature: 22
- service: climate.set_temperature
  data:
    hvac_mode: heat
    temperature: 22
- service: climate.set_temperature
  data:
    hvac_mode: heat
    temperature: 22

current_slot: 3
next_slot: 0
next_trigger: 2025-03-31T00:00:00+03:00
tags: 
icon: mdi:calendar-clock
friendly_name: Climate BathR1
```
![Image](https://github.com/user-attachments/assets/dc7a1dc3-37be-49a6-aa25-ddc4896a9023)
```
weekdays: daily
timeslots: 00:00:00 - 06:00:00, 06:00:00 - 22:00:00, 22:00:00 - 00:00:00
entities: climate.sth_southr
actions: 
- service: climate.set_temperature
  data:
    hvac_mode: heat
    temperature: 19
- service: climate.set_temperature
  data:
    hvac_mode: heat
    temperature: 19
- service: climate.set_temperature
  data:
    hvac_mode: heat
    temperature: 19.5

current_slot: 2
next_slot: 0
next_trigger: 2025-03-31T00:00:00+03:00
tags: 
icon: mdi:calendar-clock
friendly_name: Climate SouthR
```
