### ISSUE TITLE
Feature request: one-time schedules service

### ISSUE THREAD

**Issue by eduperez** [nielsfaber/scheduler-component#56]
Using the scheduler component service, I can easily program a task to be executed at a certain time; for example with this simple code:

```
    - service: scheduler.add
      data:
        actions:
          - service: turn_off
            entity: switch.sirena
        entries:
          - time: '{{ states(''input_datetime.caldera_manual_hora'') }}'
            actions:
              - 0
```

However, I cannot make this a one-time event, it is always scheduled to be executed each day. I though could write a script and call the `scheduler.remove` service as part of the action, but I cannot know which `entity_id` to use.

Thanks!

**Comment by KTibow** [comment]
Look at the scheduler-card, it has an option to disable a schedule automatically after triggering.

**Comment by eduperez** [comment]
Yes, I know about the scheduler card, and it's fantastic, thanks. But I would like to be able to create one-time schedules from a script, too.

**Comment by KTibow** [comment]
Ask @nielsfaber about how that works, I don't know except how to use the GUI for it.

**Comment by nielsfaber** [comment]
In principle all features of the scheduler-card are available using that service, but not very well documented..
There is currently no support for making a self-destructing schedule (but it will come soon), only one that turns off after triggering.
Templates are not supported either, so I don’t think your code example would work.

IMO the whole point of this component is to store entries created by the UI editor / card.
But ofcourse you’re free to use it.

**Comment by KTibow** [comment]
@nielsfaber support for templates in regular `data` without needing `data_template` in service calls in scripts/automations was added recently.

**Comment by eduperez** [comment]
The template is working fine, thanks.

I found can add a "run_once" option like this:
```
    - service: scheduler.add
      data:
        actions:
          - service: turn_off
            entity: switch.sirena
        entries:
          - time: '{{ states(''input_datetime.caldera_manual_hora'') }}'
            actions:
              - 0
        options:
          run_once: true
```

Unfortunately, this does not seem to be supported.

There is also an entry to give a name to the schedule, but not an entity_id, as required by the remove service.
