### ISSUE TITLE
Schedule to trigger on a date

### ISSUE THREAD

**Issue by ntompson** [nielsfaber/scheduler-component#88]
Hi,

I've just discovered your awesome integration / card and am working through my time based automations, converting to scheduler. But I have a few automations that trigger on a specific date, which I can't convert.

Typically these are one offs that get programmed for a specific occasion: for example, guest mode from and until people stay in our house, or holiday mode for when we leave the house for an extended period.

I'd love it if I could set a specific date to trigger the necessary automation, after which the scheduled item deactivates and stays in the list ready for the next time I need to use it.

Thanks for your great work!

**Comment by nielsfaber** [comment]
Scheduler is intended for tasks that repeat on a weekly basis.
It does not handle a start / stop date interval.

I can think of two alternative ways to accomplish this:
1. Enable/disable such schedules by means of an automation that handles the date interval
2. Add a condition entity to the schedules which represents whether the current date is inside the date interval

Your request may be a good improvement, but it would take some effort to add it.
I'm afraid my priorities are currently elsewhere, but I might pick this up at a later point.

**Comment by ntompson** [comment]
Thanks for the thoughtful comments. I understand why this may not be straight forward. 

I was attracted to using Scheduler for its elegance compared to time based automation triggers in HA. For example, I have an automation that ends holiday mode when a pre-defined timestamp stored in an `input_datetime` is reached:

```yaml
  # End holiday mode
  - alias: End holiday
    trigger:
      platform: template
      value_template: >
        {{ (states('sensor.date_time') 
            == (state_attr('input_datetime.holiday_return', 'timestamp') 
              | int | timestamp_custom('%Y-%m-%d, %H:%M', True)))
        }}
    ...
```

Which isn't very pretty.

I had in mind that, where currently Scheduler offers the options of Daily, Workdays, Weekend and Choose, a fifth "Time stamp" could be added, in which a simple date time picker could be offered to set the timestamp. The "Behaviour after triggering" option could be auto set to "Stop".

But I appreciate that the implementation may be more effort than it sounds...
